### ISSUE TITLE
Real Headlines for Content Box

### ISSUE THREAD

**Issue by sstehle** [kickstartDS/kickstartDS#1243]
As content editor I would like to be able to use real headlines in the **Content Boxes** in addition to the topics.

**Comment by julrich** [comment]
I think we've debated this before internally. We might change that going forward, but you can already get that behavior today by using the `renderTopic` function of a `ContentBox`:
https://github.com/kickstartDS/kickstartDS/blob/next/packages/components/base/source/content-box/ContentBoxComponent.tsx#L13

This allows customization for the rendering of the `topic` property, for example to use a `<Headline/>` component instead of a simple `string`. Additionally (if it should be shown in Storybook) you'd just need to extend the schema, too:
https://github.com/kickstartDS/kickstartDS/blob/next/packages/components/base/source/content-box/content-box.schema.json

We did something quite similar to add multiple buttons to a `Visual` component for our own application of **kickstartDS** here:
- https://github.com/kickstartDS/kickstartDS-storybook/blob/master/src/visual/visual.schema.json
- https://github.com/kickstartDS/kickstartDS-storybook/blob/master/src/visual/VisualComponent.jsx

**Comment by lmestel** [comment]
related: #281

**Comment by DanielLeyUX** [comment]
duplicate
